### ISSUE TITLE
FOV getting clipped in enhanced mean image and in cell detection

### ISSUE THREAD

**Issue by rajatsaxena** [MouseLand/suite2p#125]
The images below should make the issue clear. The first two images are of _enhanced mean_  with and without ROI overlaid. The last two images are of _mean_  with and without ROI. Some area of the FOV is getting clipped off (mostly at the bottom and right edge) the _enhanced mean image_ which is present in the _mean image_. Note that this problem does not occur in the Matlab version. Is their parameter setting that could have caused it? I can upload the scripts used to run this data. Thanks a lot. 

![capture1](https://user-images.githubusercontent.com/5181888/49493703-eb437800-f811-11e8-9e96-7373837e2c72.PNG)
![capture2](https://user-images.githubusercontent.com/5181888/49493704-ebdc0e80-f811-11e8-8599-c2872761cf52.PNG)
![capture3](https://user-images.githubusercontent.com/5181888/49493705-ebdc0e80-f811-11e8-9652-c92915f61b01.PNG)
![capture4](https://user-images.githubusercontent.com/5181888/49493706-ebdc0e80-f811-11e8-9521-8f0ec8495e1a.PNG)

**Comment by carsen-stringer** [comment]
During registration we find the shifts in XY of the FOV, the maximum of these shifts determines the total possible area that can be used for cell extraction (we can't use areas that are always shifted out of the microscope). So we only extract cells on this smaller region (ops['yrange'], ops['xrange']), but then we define the cells' pixels based on their position in the full FOV. The edge effects could be due to the motion because it's the whole FOV. 

But I don't understand why the image was not cropped there. When you ran with the matlab version, were the ops.yrange and ops.xrange shorter?

Another possibility is that this is nonrigid movement. Did you run the matlab with nonrigid registration? You could try running the python with nonrigid (set nonrigid=1). You can watch the video of the registered binary in the GUI and see if it's screwing up the registration, or check the registration metrics. (recommend using the github version too for each of these in case you aren't)

**Comment by rajatsaxena** [comment]
The `ops.xrange` = [10,790] and `ops.yrange`=[15,486] for the matlab version whereas the `ops.xrange`=[7,760] and `ops.yrange=[10,458] for the python run for the same file. We used rigid registration for both of them. 
Yes, I understand the possibility wrt non-rigid movement but shouldn't the result be same (or similar?) for both matlab and python. Thank you for your help!

**Comment by carsen-stringer** [comment]
We do have slightly different default settings for rigid registration in the matlab and python versions. But the cropping is not that much more from the matlab version, do you still a ridge at the edge of ops.mimg1 in the matlab version?

The non-rigid registration should work better in the python version - we first run rigid registration and then run non-rigid registration, which makes it less susceptible to outliers I think. Regardless I'd recommend looking at the registration metrics and trying it with 'nonrigid'=1.

**Comment by rajatsaxena** [comment]
No, I do not see a ridge in the Matlab version. Yes, I ran the suite2p with non-rigid registration in python but still, the cell detection area is getting clipped in that.

**Comment by carsen-stringer** [comment]
Can I see what it looks like in the GUI (mean image with ROIs overlaid)?

**Comment by rajatsaxena** [comment]
![capture](https://user-images.githubusercontent.com/5181888/50024268-a6001280-ff96-11e8-80a2-c5d1bd923694.PNG)
![capture2](https://user-images.githubusercontent.com/5181888/50024269-a6001280-ff96-11e8-8f36-3cc92cf70d1f.PNG)

**Comment by rajatsaxena** [comment]
I looked at the "badframes" in ops and it matches what you said. Thanks for clearing it out.

**Comment by marius10p** [comment]
I have pushed a version that computes bad frames and excludes them from the clipping range. Let me know if it works, otherwise I will expose the parameter that thresholds the confidence values for determining a bad frame.

**Comment by dmnburrows** [comment]
hi there,

I've downloaded the most recent github version of suite2p but i am still getting the same clipping issue on my data (first image is mean and second is enhanced mean)

<img width="2560" alt="screenshot 2018-12-20 at 16 34 09" src="https://user-images.githubusercontent.com/45342427/50297695-524d6780-0475-11e9-9003-676e84923d09.png">
<img width="2560" alt="screenshot 2018-12-20 at 16 34 49" src="https://user-images.githubusercontent.com/45342427/50297721-5e392980-0475-11e9-8e04-098d17e26c92.png">

**Comment by marius10p** [comment]
You should look at the registered binary (drop-down in the GUI) to see on what frames the large X and Y offsets are found. 

You can also reduce 'maxregshift', which is the maximum allowed registration offset. Your maximum possible shifts are probably very small, right? Our default is 0.1, as a fraction of the respective X and Y dimensions.
