### ISSUE TITLE
issues of locating ops.npy and db.npy 

### ISSUE THREAD

**Issue by Ququkiwi** [MouseLand/suite2p#662]
Greetings: 
 It seems that suite2p program has issues in locating ops.npy and db.npy files. 
Below is the error message I received with attempts of running suite2p
>>>ERROR<<<
usage: __main__.py [-h] [--single_plane] [--ops OPS] [--db DB]
                   [--look_one_level_down LOOK_ONE_LEVEL_DOWN]
                   [--fast_disk FAST_DISK] [--delete_bin DELETE_BIN]
                   [--mesoscan MESOSCAN] [--bruker BRUKER] [--h5py H5PY]
                   [--h5py_key H5PY_KEY] [--save_path0 SAVE_PATH0]
                   [--save_folder SAVE_FOLDER] [--subfolders SUBFOLDERS]
                   [--move_bin MOVE_BIN] [--nplanes NPLANES]
                   [--nchannels NCHANNELS] [--functional_chan FUNCTIONAL_CHAN]
                   [--tau TAU] [--fs FS] [--force_sktiff FORCE_SKTIFF]
                   [--frames_include FRAMES_INCLUDE]
                   [--multiplane_parallel MULTIPLANE_PARALLEL]
                   [--ignore_flyback IGNORE_FLYBACK]
                   [--preclassify PRECLASSIFY] [--save_mat SAVE_MAT]
                   [--save_NWB SAVE_NWB] [--combined COMBINED]
                   [--aspect ASPECT] [--do_bidiphase DO_BIDIPHASE]
                   [--bidiphase BIDIPHASE] [--bidi_corrected BIDI_CORRECTED]
                   [--do_registration DO_REGISTRATION]
                   [--two_step_registration TWO_STEP_REGISTRATION]
                   [--keep_movie_raw KEEP_MOVIE_RAW] [--nimg_init NIMG_INIT]
                   [--batch_size BATCH_SIZE] [--maxregshift MAXREGSHIFT]
                   [--align_by_chan ALIGN_BY_CHAN] [--reg_tif REG_TIF]
                   [--reg_tif_chan2 REG_TIF_CHAN2] [--subpixel SUBPIXEL]
                   [--smooth_sigma_time SMOOTH_SIGMA_TIME]
                   [--smooth_sigma SMOOTH_SIGMA] [--th_badframes TH_BADFRAMES]
                   [--norm_frames NORM_FRAMES] [--force_refImg FORCE_REFIMG]
                   [--pad_fft PAD_FFT] [--nonrigid NONRIGID]
                   [--block_size BLOCK_SIZE [BLOCK_SIZE ...]]
                   [--snr_thresh SNR_THRESH] [--maxregshiftNR MAXREGSHIFTNR]
                   [--1Preg 1PREG] [--spatial_hp SPATIAL_HP]
                   [--spatial_hp_reg SPATIAL_HP_REG]
                   [--spatial_hp_detect SPATIAL_HP_DETECT]
                   [--pre_smooth PRE_SMOOTH] [--spatial_taper SPATIAL_TAPER]
                   [--roidetect ROIDETECT] [--spikedetect SPIKEDETECT]
                   [--anatomical_only ANATOMICAL_ONLY]
                   [--cellprob_threshold CELLPROB_THRESHOLD]
                   [--flow_threshold FLOW_THRESHOLD]
                   [--sparse_mode SPARSE_MODE] [--diameter DIAMETER]
                   [--spatial_scale SPATIAL_SCALE] [--connected CONNECTED]
                   [--nbinned NBINNED] [--max_iterations MAX_ITERATIONS]
                   [--threshold_scaling THRESHOLD_SCALING]
                   [--max_overlap MAX_OVERLAP] [--high_pass HIGH_PASS]
                   [--denoise DENOISE] [--soma_crop SOMA_CROP]
                   [--neuropil_extract NEUROPIL_EXTRACT]
                   [--inner_neuropil_radius INNER_NEUROPIL_RADIUS]
                   [--min_neuropil_pixels MIN_NEUROPIL_PIXELS]
                   [--lam_percentile LAM_PERCENTILE]
                   [--allow_overlap ALLOW_OVERLAP]
                   [--use_builtin_classifier USE_BUILTIN_CLASSIFIER]
                   [--classifier_path CLASSIFIER_PATH]
                   [--chan2_thres CHAN2_THRES] [--baseline BASELINE]
                   [--win_baseline WIN_BASELINE] [--sig_baseline SIG_BASELINE]
                   [--prctile_baseline PRCTILE_BASELINE] [--neucoeff NEUCOEFF]
__main__.py: error: unrecognized arguments: C\.suite2p\ops\ops.npy C\.suite2p\ops\db.npy
Interrupted by error (not finished)

     I tried with my own data (sbx and tif format), still got the same error message; I tried with the sample data provided here and got the same error message, too.  
      Reinstallation and upgrade is not helping, neither. 

     Any suggestion or information will be very appreciated and helpful. 

Best,
Zhongmin

**Comment by carsen-stringer** [comment]
Where is this error showing up? Can you send a picture/text from command line and text window from GUI? You can see what my running looks like after adding a path to the data_path below. I'm wondering if the file browser is messed up somehow for you?

![image](https://user-images.githubusercontent.com/15067541/116782520-91cdea80-aa57-11eb-9c44-00e89e58b215.png)

**Comment by Ququkiwi** [comment]
Hi, Carsen:
      Thank you so much for your great suggestions.
      Attached are screenshots of using anaconda powershell prompt or just
prompt. It looks like the same error messages keep showing up.
      Do you think re-installation of python may help?

      Any further suggestions or information will be appreciated and
helpful.

Best,
Zhongmin

**Comment by carsen-stringer** [comment]
I can't see the image unfortunately, can you post it on github directly?

**Comment by Ququkiwi** [comment]
![suite2P with bugs screenshot 2 with anaconda prompt-ZL-5-1-21](https://user-images.githubusercontent.com/34487626/116846614-84bb1380-ab9d-11eb-85d1-df7e217be2c8.png)
![suite2P with bugs screenshot 1 with anaconda prompt-ZL-5-1-21](https://user-images.githubusercontent.com/34487626/116846632-94d2f300-ab9d-11eb-9f0f-2e8447b09c4c.png)
![suite2P with bugs screenshot 1-ZL-5-1-21](https://user-images.githubusercontent.com/34487626/116846638-98ff1080-ab9d-11eb-836d-b0a389ff2423.png)
![suite2P with bugs screenshot 2-ZL-5-1-21](https://user-images.githubusercontent.com/34487626/116846655-a1574b80-ab9d-11eb-8494-2b2a86009b64.png)

**Comment by Ququkiwi** [comment]
Hi, Carsen:
      Sorry for the inconvenience. Please let me know if the screenshots can be viewed properly. 

Best,
Zhongmin

**Comment by carsen-stringer** [comment]
hmm this is the latest code? I tried running as admin and still can't replicate this error. I think I know what the error is -- your pathlib $HOME directory is something weird -- but I'm not sure why. On my windows computer, whether or not I run as admin, the ops.npy and db.npy files get saved to C:\Users\carse\.suite2p\ops\ . You can check your $HOME directory by running python in the environment (with command `python`) and then running these commands 
```
import pathlib
print(pathlib.Path.home())
```

**Comment by Ququkiwi** [comment]
![Screenshot after checking homedirectory-5-3-21](https://user-images.githubusercontent.com/34487626/116922420-35f79300-ac0a-11eb-82c0-2be9bc83d23e.png)
Hi, Carsen:
       Thank you so much for your great suggestions :) I just ran these commands and the directory went back to C:\Users\Image C. 
       Any further suggestions will be very appreciated and helpful. 

Best,
Zhongmin

**Comment by carsen-stringer** [comment]
Ah there is a space in your user name and a C, I thought the C was the C:\ drive! Can you try this command

print(pathlib.Path.home().joinpath('.suite2p').joinpath('ops'))

I think pathlib is angry about that space

**Comment by Ququkiwi** [comment]
![Screenshot of attempt of directory change](https://user-images.githubusercontent.com/34487626/116926623-6c83dc80-ac0f-11eb-80be-e077ab9512d9.png)
Hi, Carsen:
      Thank you very much for your suggestions :) I just tried this command, it returned with "unable to initialize device PRN". 
Best,
Zhongmin

**Comment by carsen-stringer** [comment]
Oh sorry run it in python like you did before please

**Comment by Ququkiwi** [comment]
Will do, thanks!

**Comment by Ququkiwi** [comment]
![image](https://user-images.githubusercontent.com/34487626/116935634-7c092280-ac1b-11eb-8bf3-f10ec4a567d8.png)
Here is the screenshot :)

**Comment by Ququkiwi** [comment]
![image](https://user-images.githubusercontent.com/34487626/116953038-13cd3780-ac41-11eb-89ad-3501366c6bcb.png)
Hi, Carsen:
     Thank you very much for your great suggestions and generous help :) 
     After creating another user account without space and then install python and suite2p, it works nicely for your sample data! :) 

Best,
Zhongmin

**Comment by RichieHakim** [comment]
@carsen-stringer 
I'm also having this issue. Is it possible to fix this bug without making a new user on the computer? Willing to patch it myself if you can point to the code in question. Thanks Carsen! The new update looks amazing.

**Comment by RichieHakim** [comment]
Looks like running it in python directly (jupyter notebook) works:

`
ops = suite2p.default_ops()
db = {
    'data_path': ['D:\RH_local\data\scanimage data\20210527\gcamp8f_test'],
    'save_path0': 'D:\RH_local\data\scanimage data\20210527\gcamp8f_test',
}
suite2p.run_s2p(ops=ops, db=db)
`

**Comment by carsen-stringer** [comment]
this should be working now on the github version of the code, but I don't actually have a computer with a space in the username to test, will make a new pip soon too

**Comment by AntoineMal** [comment]
Hi all!

I have the same problem with my path... 
I still have this issue in the GUI, even with the latest release of the GIT. 

I can't run it on jupyter too, it seems my tif files are not accepted by ScanImageTiffReader function... The error message if below.

Best,

Antoine

NOTE: ScanImageTiffReader not working for this tiff type, using tifffile
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In [19], line 1
----> 1 output_ops = suite2p.run_s2p(ops=ops, db=db)

File ~\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:394, in run_s2p(ops, db, server)
    392         ops0 = ops0[0]
    393 else:
--> 394     ops0 = io.tiff_to_binary(ops.copy())
    395 plane_folders = natsorted([ f.path for f in os.scandir(save_folder) if f.is_dir() and f.name[:5]=='plane'])
    396 ops_paths = [os.path.join(f, 'ops.npy') for f in plane_folders]

File ~\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py:135, in tiff_to_binary(ops)
    132 ntotal=0
    133 for ik, file in enumerate(fs):
    134     # open tiff
--> 135     tif, Ltif = open_tiff(file, use_sktiff)
    136     # keep track of the plane identity of the first frame (channel identity is assumed always 0)
    137     if ops['first_tiffs'][ik]:

File ~\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py:79, in open_tiff(file, sktiff)
     77 """ Returns image and its length from tiff file with either ScanImageTiffReader or tifffile, based on 'sktiff'"""
     78 if sktiff:
---> 79     tif = TiffFile(file)
     80     Ltif = len(tif.pages)
     81 else:

File ~\anaconda3\envs\suite2p\lib\site-packages\tifffile\tifffile.py:3832, in TiffFile.__init__(self, file, mode, name, offset, size, omexml, _multifile, _useframes, _parent, **is_flags)
   3829 if mode not in (None, 'r', 'r+', 'rb', 'r+b'):
   3830     raise ValueError(f'invalid mode {mode!r}')
-> 3832 fh = FileHandle(file, mode=mode, name=name, offset=offset, size=size)
   3833 self._fh = fh
   3834 self._multifile = True if _multifile is None else bool(_multifile)

File ~\anaconda3\envs\suite2p\lib\site-packages\tifffile\tifffile.py:13088, in FileHandle.__init__(self, file, mode, name, offset, size)
  13086 self._close = True
  13087 self._lock = NullContext()
> 13088 self.open()
  13089 assert self._fh is not None

File ~\anaconda3\envs\suite2p\lib\site-packages\tifffile\tifffile.py:13103, in FileHandle.open(self)
  13101 self._file = os.path.realpath(self._file)
  13102 self._dir, self._name = os.path.split(self._file)
> 13103 self._fh = open(self._file, self._mode)  # type: ignore
  13104 self._close = True
  13105 if self._offset < 0:

OSError: [Errno 22] Invalid argument: 'F:\\Antoine\todo\\stim\\Tiff\\Series7.tif'

**Comment by felixsmli** [comment]
I'm still having this same problem on Windows. But here is another workaround (that does *not* require you to create a new user):
1. Find or create a dir that has no space in the path, e.g., `D:\fake_user`.
2. In your conda environment for Suite2p (i.e., after `conda activate suite2p`), run `conda env config vars set USERPROFILE=D:\fake_user`.
3. Use as usual. There may be another error prompt saying it cannot find "D:\fake_user\Desktop". This can be safely ignored, or you can create that dir.

Alternatively you can find and edit [this line](https://github.com/MouseLand/suite2p/blob/c88e1ba3aa2013fe379e64c7e45ae73a417eb4a7/suite2p/gui/gui2p.py#L49C9-L49C60) and replace the `pathlib.Path.home()` part with `pathlib.Path("D:\fake_user")` or any other paths with no space.
