### ISSUE TITLE
Directory address work around

### ISSUE THREAD

**Issue by tharmon0118** [MouseLand/suite2p#678]
Hello, 

I'm encountering an issue when loading the default ops.npy and db.npy file that I think is caused by a space in the directory address to the .suite2p folder. The address for the folder is  'C:\Users\Mooney Lab\.suite2p\ops' and the error message reads 'error: unrecognized argument: Lab\.suite2p\ops\ops.npy Lab\.suite2p\ops\db.npy'. I tried moving the Anaconda base folder, but this created some separate issues. I think changing the folder name would create similar issues. Is there a way to move the location of the .suite2p folder? I'm unsure how it is assigned and indexed to in the program.

Thank you,
Tom Harmon

**Comment by RichieHakim** [comment]
Many people are having this issue. A simple (albeit limiting) work around is to not use the GUI and run suite2p from python / a jupyter notebook directly. Carsen is aware of the issue I believe. See here: [](https://github.com/MouseLand/suite2p/issues/662)

**Comment by tharmon0118** [comment]
Ah ok. Yes, it looks like the exact same problem. Thanks for looping me in!

**Comment by carsen-stringer** [comment]
this should be working now on the github version of the code, but I don't actually have a computer with a space to test, will make a new pip soon too

**Comment by RichieHakim** [comment]
@carsen-stringer 

Hi, thanks for working on this problem. I tested this out again today and it doesn't seem to be working (tried installing a fresh environment from the main branch). I also tried installing a virtual environment on a disk without a space in the user path, so I think the error must be due to some default path search being done in suite2p. Specifically: `C:\Users\Rich Hakim\.suite2p\ops`
Have you had a chance to write any tests for this?

Specifically, on Windows. I have a user path: `C:\Users\Rich Hakim` and I think space is likely causing the issue.

Thanks again!

This is the error that comes in the suite2p run terminal:
```
Warning: cellpose did not import
No module named 'cellpose'
cannot use anatomical mode, but otherwise suite2p will run normally
>>>ERROR<<<
usage: __main__.py [-h] [--single_plane] [--ops OPS] [--db DB] [--version]
                   [--suite2p_version SUITE2P_VERSION]
                   [--look_one_level_down LOOK_ONE_LEVEL_DOWN]
                   [--fast_disk FAST_DISK] [--delete_bin DELETE_BIN]
                   [--mesoscan MESOSCAN] [--bruker BRUKER]
                   [--bruker_bidirectional BRUKER_BIDIRECTIONAL] [--h5py H5PY]
                   [--h5py_key H5PY_KEY] [--nwb_file NWB_FILE]
                   [--nwb_driver NWB_DRIVER] [--nwb_series NWB_SERIES]
                   [--save_path0 SAVE_PATH0] [--save_folder SAVE_FOLDER]
                   [--subfolders SUBFOLDERS] [--move_bin MOVE_BIN]
                   [--nplanes NPLANES] [--nchannels NCHANNELS]
                   [--functional_chan FUNCTIONAL_CHAN] [--tau TAU] [--fs FS]
                   [--force_sktiff FORCE_SKTIFF]
                   [--frames_include FRAMES_INCLUDE]
                   [--multiplane_parallel MULTIPLANE_PARALLEL]
                   [--ignore_flyback IGNORE_FLYBACK]
                   [--preclassify PRECLASSIFY] [--save_mat SAVE_MAT]
                   [--save_NWB SAVE_NWB] [--combined COMBINED]
                   [--aspect ASPECT] [--do_bidiphase DO_BIDIPHASE]
                   [--bidiphase BIDIPHASE] [--bidi_corrected BIDI_CORRECTED]
                   [--do_registration DO_REGISTRATION]
                   [--two_step_registration TWO_STEP_REGISTRATION]
                   [--keep_movie_raw KEEP_MOVIE_RAW] [--nimg_init NIMG_INIT]
                   [--batch_size BATCH_SIZE] [--maxregshift MAXREGSHIFT]
                   [--align_by_chan ALIGN_BY_CHAN] [--reg_tif REG_TIF]
                   [--reg_tif_chan2 REG_TIF_CHAN2] [--subpixel SUBPIXEL]
                   [--smooth_sigma_time SMOOTH_SIGMA_TIME]
                   [--smooth_sigma SMOOTH_SIGMA] [--th_badframes TH_BADFRAMES]
                   [--norm_frames NORM_FRAMES] [--force_refImg FORCE_REFIMG]
                   [--pad_fft PAD_FFT] [--nonrigid NONRIGID]
                   [--block_size BLOCK_SIZE [BLOCK_SIZE ...]]
                   [--snr_thresh SNR_THRESH] [--maxregshiftNR MAXREGSHIFTNR]
                   [--1Preg 1PREG] [--spatial_hp SPATIAL_HP]
                   [--spatial_hp_reg SPATIAL_HP_REG]
                   [--spatial_hp_detect SPATIAL_HP_DETECT]
                   [--pre_smooth PRE_SMOOTH] [--spatial_taper SPATIAL_TAPER]
                   [--roidetect ROIDETECT] [--spikedetect SPIKEDETECT]
                   [--anatomical_only ANATOMICAL_ONLY]
                   [--cellprob_threshold CELLPROB_THRESHOLD]
                   [--flow_threshold FLOW_THRESHOLD]
                   [--sparse_mode SPARSE_MODE] [--diameter DIAMETER]
                   [--spatial_scale SPATIAL_SCALE] [--connected CONNECTED]
                   [--nbinned NBINNED] [--max_iterations MAX_ITERATIONS]
                   [--threshold_scaling THRESHOLD_SCALING]
                   [--max_overlap MAX_OVERLAP] [--high_pass HIGH_PASS]
                   [--denoise DENOISE] [--soma_crop SOMA_CROP]
                   [--neuropil_extract NEUROPIL_EXTRACT]
                   [--inner_neuropil_radius INNER_NEUROPIL_RADIUS]
                   [--min_neuropil_pixels MIN_NEUROPIL_PIXELS]
                   [--lam_percentile LAM_PERCENTILE]
                   [--allow_overlap ALLOW_OVERLAP]
                   [--use_builtin_classifier USE_BUILTIN_CLASSIFIER]
                   [--classifier_path CLASSIFIER_PATH]
                   [--chan2_thres CHAN2_THRES] [--baseline BASELINE]
                   [--win_baseline WIN_BASELINE] [--sig_baseline SIG_BASELINE]
                   [--prctile_baseline PRCTILE_BASELINE] [--neucoeff NEUCOEFF]
__main__.py: error: unrecognized arguments: Hakim\.suite2p\ops\ops.npy Hakim\.suite2p\ops\db.npy
Interrupted by error (not finished)

```

**Comment by RichieHakim** [comment]
@carsen-stringer 
This issue is not resolved. Please let me know if I can help solve it. If you point me in the right direction, I'm happy to try making a PR.
