### ISSUE TITLE
Failed to merge ROI 

### ISSUE THREAD

**Issue by Jessica0218** [MouseLand/suite2p#860]
Hi，
I tried to merge  two ROIs selected in the GUI
but the following error occurred
![捕获](https://user-images.githubusercontent.com/73352030/179653503-cbecda43-4455-4405-82a4-54c5f7cece21.PNG)

I don't know what‘s going wrong

thanks for your help

**Comment by carsen-stringer** [comment]
sorry this was a bug, it is fixed now please `pip install suite2p --upgrade`

**Comment by faezehrabbani97** [comment]
Hi 
I have the last version of Suite2p 'suite2p v0.11.1' and this problem still exist
![image](https://user-images.githubusercontent.com/101398285/206675806-33a75332-e143-46fa-8f28-132cb2b8e06b.png)
